server:
  port: ${AUTH_SERVICE_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  mail:
    from: ${MAIL_FROM}
    from-name: ${MAIL_FROM_NAME}
  bootstrap:
    admin:
      email: ${BOOTSTRAP_ADMIN_EMAIL:}
      password: ${BOOTSTRAP_ADMIN_PASSWORD:}

jwt:
  secret: ${JWT_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  refresh-token-session-expiration: ${JWT_REFRESH_TOKEN_SESSION_EXPIRATION}

